### ISSUE TITLE
Can someone please work on following issues in this lab

### ISSUE THREAD

**Issue by GhumanNavneet** [Microsoft/MCW-Securing-PaaS#5]
- In Exercise 5 Task 5, I did not get any output as step 6. 
- The browser is actually not allowing to download the file
- In Exercise 6 Task 1, there is no project in the \WebApp\FourthCoffeeWeb.sln as per step 12.
- The path to the project is not correct. Also tried to manually extract the file but still the project was empty when opened in Visual Studio
- Also in the last exercise, KeyVaultAuditor is not able to open the Log Analytics. Clicking on Log Analytics is forwarding me to OMS workspace page.

**Comment by givenscj** [comment]
I have added extra hints and notes for these.  Depending on the browser the Json may or may not display, or it may prompt to download it.  

Updated to open the web app as a folder in case it doesn't open properly.  

For the last one you would have switched back to your tenant admin account before you made it to the last exercise, we didn't go as far as to design that exercise to be run as that specific account.

**Comment by DawnmarieDesJardins** [comment]
Hi GhumanNavneet,
I've just pushed through the December test/fix that @givenscj has been working on.  As he mentioned above, he's added extra hints and notes for lab users.  Closing this issue as fixed.  Please let us know if you need further assistance.
